---
LOGGED_MODEL : "model_config"
LOOKUP_TABLE_PATH : "lookup_table"
MODEL_ATTRIB_PATH : "model_data"
IMAGE_PATH : "images"
POLICY_DTYPE_DICT : {'policy_number': 'str'}
DATE_COLS : ['proposal_received_date', 'policy_issue_date']
NA_VALUES : ['', 'NA', 'N/A', 'NULL', 'null', '?', '*', '#N/A', '#VALUE!']
AGENT_DTYPE_DICT : {'agent_code': 'str'}
ZIPCODE_DTYPE_DICT : {'zipcode': 'str'}
COLS_TO_REM_ONLINE : ['proposal_received_date','policy_issue_date', 'zipcode', 'county', 'state', 'agent_code', 'agent_dob', 'agent_doj']
COLS_TO_REM_BATCH : ['proposal_received_date','policy_issue_date', 'zipcode', 'county', 'state', 'agent_code']
MISSING_COLS : ['agent_persistency']
ONE_HOT_COLS : ['owner_gender', 'marital_status', 'smoker', 'medical', 'education', 'occupation', 'payment_freq', 'agent_status', 'agent_education']
FEATURES : ['owner_age', 'owner_gender', 'marital_status', 'num_nominee', 'smoker',
       'medical', 'education', 'occupation', 'experience', 'income',
       'negative_zipcode', 'family_member', 'existing_num_policy',
       'has_critical_health_history', 'policy_term', 'payment_freq',
       'annual_premium', 'sum_insured', 'agent_status', 'agent_education',
       'agent_age', 'agent_tenure_days', 'agent_persistency',
       'last_6_month_submissions', 'average_premium', 'is_reinstated',
       'prev_persistency', 'num_complaints', 'target_completion_perc',
       'has_contacted_in_last_6_months', 'credit_score',
       'time_to_issue', 'prem_to_income_ratio']
COLUMN_MAPPING : {'Education':'education', 'Occupation':'occupation','Smoker':'smoker',
                  'Marital Status':'marital_status', 'Gender':'owner_gender', 'Experience':'experience', 
                  'Income':'income', 'Age':'owner_age','Lapse':'lapse',
                  'Credit Score':'credit_score','Policy Term':'policy_term','Payment Frequency':'payment_freq', 
                  'Annual Premium':'annual_premium', 'Sum Insured':'sum_insured','Agent Age':'agent_age', 
                  'Agent Tenure (days)':'agent_tenure_days', 'Persistency':'agent_persistency', 'Last 6 months policies':'last_6_month_submissions', 
                  'Average Premium':'average_premium','Is Reinstated?':'is_reinstated', 'Persistency before Reinstated':'prev_persistency', 
                  'Number Complaints':'num_complaints', 'Agent Status':'agent_status', 'Agent Education':'agent_education', 
                  'Target Completion Percentage':'target_completion_perc','Number of Nominees':'num_nominee','Underwent Medical Test?': 'medical', 
                  'Number of Family Members': 'family_member', 'Number Existing Policies': 'existing_num_policy', 
                  'Has Critical Health History?' : 'has_critical_health_history'}